import Head from 'next/head'

export default function Header () {
    return(
        <Head>
            <title>Coffee connouiser app -Nextjs</title>
            <meta name="description" content="Generated by create next app" />
            <meta property="og:title" content="coffee conniouser app" key="title" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}