import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Footer from '../components/Footer'
import Head from 'next/head'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee connouiser app -Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content="coffee conniouser app" key="title" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
      </main>

      <Footer></Footer>
    </div>
  )
}